### ISSUE TITLE
accelerate convergence scheme

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#159]
consider implementing automatic convergence in which the model (either absolute fluxes or final observables) are sampled at multiple numbers of triangles and mesh_init_phi and extrapolated to obtain better precision and an estimate on the model uncertainty

**Comment by horvatm** [comment]
Numerical experiments show that in order to acceleration scheme to work we have at least two approaches ( N - number of triangles):

A. For each N we generate meshes M(N,seed) and calculate average f(t,N) = <flux(t)>_{M(N,seed)} and standard deviation sigma_flux(t,N) and then using fitting model
```
f(t,N) = f(t,infty) + a_1(t)/N + a_2(t)/N^2 + .. + epsilon(t,N)
```
for each time stamp t separately, where we know epsilon ~ N(0, sigma_flux(t,N))

B. Start with a set of meshes composed of N_0 triangles M_0 = M(N_0, seed) and then use subdivision technique to get finer meshes 
```
M_i = subdivision{M_{i-1}}   with triangles   N_1, N_2, ... 
```
where for mid-edge subdivision N_i = 4*N_{i-1}. Next calculate the average fluxes f(t, N_i) = <flux(t)>_{M_i} and sigma_flux(t, N_i) for each set of meshes M_i and fit model as given above.  As the refinement is systematic I would expect that  f(t,N_i) as function of N is smoother then in the case A and this property favored by extrapolation.

**Comment by horvatm** [comment]
I won't continue this path.
