### ISSUE TITLE
rename overcontact->contact

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#166]
...to match language used in the release paper.

We also need to decide what to use for the default component-label of the envelope in a contact system - we currently have the *kind* as 'envelope' and the default *component-label* as 'common_envelope'.  @aprsa @gecheline - any thoughts/opinions?

**Comment by gecheline** [comment]
I propose 'contact_binary' for the default Bundle label (as opposed to just 'contact') and 'contact_envelope' for the component label, to retain the notion of two stars immersed in a common envelope. Another idea I had for the component label is 'common_atmosphere' but I really dislike it because it's not very common in literature and doesn't contain the word 'contact' which might lead to confusion for some users. Thoughts/vetoes?

**Comment by horvatm** [comment]
I like proposed names.

**Comment by kecnry** [comment]
My only reservation is the 'contact_binary' switch: the default_triple class_method currently has a switch for 'inner_as_overcontact' that will also need to be renamed... so perhaps for these switches we should use the convention of contact_[label of binary orbit].  For default_binary this would be 'contact_binary', for default_triple it would then be 'contact_inner', etc.

For that matter, maybe the default component labels should follow this same convention (and so be labeled 'contact_binary')?  This will possibly make it easier whenever we implement quadruples with two contact binaries.

**Comment by kecnry** [comment]
closed by 6701961a06c4325c195b85dc432250f2aa119a6e and PR #175
