### ISSUE TITLE
reflection fails for hot stars

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#170]
...because the bolometric passband doesn't currently cover the whole SED causing energy to be ignored within reflection.  This only becomes a problem for stars with teff > 15000.

**Comment by aprsa** [comment]
Here is a quick test of how severe this bug is w.r.t. temperature:

![bc](https://cloud.githubusercontent.com/assets/2669162/20417893/afd49166-ad16-11e6-8b43-8fe1804988ec.png)

The issue arises because we use 176nm-4um box over Castelli & Kurucz (2004) model atmospheres as our "bolometric" passband. Thus, bolometric corrections for this "bolometric" passband are significant, especially as we get towards the hotter stars, in excess of ~12000K. Our nosetest had 5000K and 10000K stars, which is within the "safe" limits, but the plot above shows that the corrections are still sorely needed. At this point it seems best to always use blackbody bolometric Inorm for reflection instead of using ck2004.

**Comment by kecnry** [comment]
using Inorm_bol_bb for reflection instead of atmospheres with the Bolometric:1760:40000 passband now gets us here (with red=phoebe1, blue=phoebe2):

![refl_compare](https://cloud.githubusercontent.com/assets/877591/20434234/f07d0758-ad74-11e6-9290-8fce6b13834e.png)

**Comment by kecnry** [comment]
stupid mistake on my part, we now agree quite well:

![refl_fixed](https://cloud.githubusercontent.com/assets/877591/20452551/646073ca-adda-11e6-8fcd-96043392326c.png)
