### ISSUE TITLE
loading matplotlib when needed  

### ISSUE THREAD

**Issue by horvatm** [phoebe-project/phoebe2#209]
Matplotlib is loaded even when it is needed. In my opinion matplotlib is not an essential part of phoebe, as the presentation of the results should be left to individual taste. This issue is especially important when we perform massive distributed non-interactive calculations.

**Comment by aprsa** [comment]
MPL import is already conditional on the ability to import: phoebe will work without it seamlessly. The frontend has some really neat wrappers written by @kecnry that should be of general interest to all phoebe users. Thus, I'm tempted to leave things as-is unless there are any convincing arguments against it.

**Comment by kecnry** [comment]
Importing matplotlib is actually a large overhead and takes up a significant amount of the time used druing `import phoebe`.  However, waiting to import until its actually needed isn't nearly as easy as it sounds, particularly for mpl since we do some magic on import that only works if its done before the user imports matplotlib manually (ie. `import phoebe` must come before `import matplotlib`).

What we may want to consider in the future when we're working on fitting and optimization, is a separate \_\_init\_\_.py for workers that is "lighter".  So the workers would import phoebe_lite instead of phoebe, for example.

**Comment by aprsa** [comment]
A one-time delay at import time is not an issue in my mind. Reducing 3 seconds by 2 seconds only once will not change anything. If this truly is to address optimization of runtime, I'd look pretty much everywhere else before here, most urgently I'd look at pieces of code that are recurring many times.

**Comment by horvatm** [comment]
I like the idea of computational intensive, non-interactive, without plotting  `phoebe_lite`.
