### ISSUE TITLE
meshes are truncated when sent through mpi

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#221]
seems that comm.send and comm.recv use pickle under-the-hood and the packet we're trying to transmit for meshes is too large, causing everything to crash.  By using comm.Send and comm.Recv we can use numpy instead of pickle, but then we need to define a buffer and type (which could make the current dictionary structure a bit more difficult).  Alternatively we *could* write meshes to disk instead of send over comm.

See this link for a similar case: https://stackoverflow.com/questions/40056005/mpi4py-mpi-err-truncate-message-truncated

**Comment by aprsa** [comment]
Funny you should bring this up, I was actually planning to shift all
communication to upper-case methods but couldn't do it quite yet as we were
passing dicts instead of numpy arrays. In addition, reusable buffers for
meshes are a way to go, so we should definitely do that. One thing we may
need to worry about is whether the buffer size is arch-dependent and does
it need any extra space for communication bits.

**Comment by aprsa** [comment]
To reproduce:

```
import phoebe
import numpy as np

phoebe.mpi_on()

b = phoebe.default_binary()

times = np.linspace(0, 1, 2)
b.add_dataset('mesh', times=times)

b.run_compute()
```

**Comment by kecnry** [comment]
Sending an appropriately sized buffer to irecv does seem to get around the issue, we just need to figure out how to estimate (or send from the workers) what size is needed.  See here: https://bitbucket.org/mpi4py/mpi4py/issues/65/mpi_err_truncate-message-truncated-when#comment-35572981
