### ISSUE TITLE
definition of vgamma inconsistent with legacy

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#234]
vgamma in phoebe2 is currently defined in the direction of positive vz and negative RV.  This is inconsistent with conventions in legacy.  We either need to change this (very easy but difficult or impossible to manage backwards compatibility) or have the legacy wrapper handle the translation and document thoroughly.

**Comment by aprsa** [comment]
I would be in favor of changing this so that positive vgamma increases the RVs (i.e. moves the RVs upwards), in agreement with legacy and with mesh RVs. I understand this breaks backwards compatibility, though, so we need to figure out what is the best way to release that. Misalignment is close to done, so perhaps bundle this fix in and release as 2.1.

**Comment by kecnry** [comment]
Fixed in development in commit 796ceb68a69d0687f16428d1e591b7ebcf35001b which will be included in the 2.1 release.

This has been addressed in 2.0.x by translating vgamma = -vga between phoebe 1 and phoebe 2 and by throwing a warning when vgamma != 0 stating that the definition will change in the 2.1 release.  These patches have been included in the 2.0.4 release in PR #235 

A note has also been added in the 2.0.x documentation noting this change in commit https://github.com/phoebe-project/phoebe2-docs/commit/a4c62f85b8b47e048d0f4700f5fadb5e3d7e019d
