### ISSUE TITLE
Import Error with MPI check during initialization

### ISSUE THREAD

**Issue by abhimat** [phoebe-project/phoebe2#357]
I’m calling PHOEBE in an emcee MCMC run that I am parallelizing through OpenMPI. When doing this on a computing cluster, some of these individual processes get run on single processor. But since the overall script gets called via openmpi, PHOEBE crashes when it is imported on one of these processes running on a single processor.

During initialization, PHOEBE detects that I am running within an openmpi environment, but since any given individual process may only be running on one processor, `self._nprocs` is 1 and the PHOEBE crashes during import because of the check on [this line](https://github.com/phoebe-project/phoebe2/blob/b3cf881031ea30f10e5ac9a79fff2250ffcbebc7/phoebe/__init__.py#L91) during import.

Is there a way to get around this issue? I was attempting to set the environment variable `PHOEBE_ENABLE_MPI` to False before importing PHOEBE, but that does not solve this issue.

**Comment by kecnry** [comment]
PHOEBE just checks for mpi4py.COMM_WORLD.comm_size() and throws an error if there is only one processor (in theory I believe that should be the **total** number of processors being used)... is there any chance that there is something wrong with your host setup that is causing those local instances to think there is only a single processor in total?  See this thread for example: https://groups.google.com/forum/#!topic/mpi4py/oGSzlTKlius

If that isn't the issue and comm_size still returns 1, then we'll need to think of a more generic solution and do some testing before releasing a bugfix for that.  So please do let me know if you find a solution through the MPI setup.  I can always move the check to only trigger if `PHOEBE_ENABLE_MPI` is True, but that is a little fine-tuned to your specific situation, so I'd rather figure out the actual cause and address it.

With all of that said - for now, if you're running from the source code and don't mind making some local edits, you should be safe to remove that if statement and error entirely, as long as you set `PHOEBE_ENABLE_MPI` to False or use phoebe.mpi_off() so that emcee handles all parallelization.

**Comment by abhimat** [comment]
Thank you for your help! In looking more into this issue since posting this, it seems it may be coming from how OpenMPI is implemented on our cluster (like in [this thread](https://stackoverflow.com/questions/29264640/mpiexec-and-python-mpi4py-gives-rank-0-and-size-1)). It seems that the size value returned by mpi4py while using OpenMPI is incorrect with our setup on our cluster.

In the meantime, switching over to using IntelMPI leads to the correct size being passed through, and this behavior is no longer a problem. I can look more into OpenMPI and why that may have been causing this issue on our cluster, and report back if I find anything. Thanks for helping out with this!

**Comment by kecnry** [comment]
Great, I'm glad that does the trick! And if you find anything we could do to detect or get around situations like this for anyone else in the future, please let us know!
