### ISSUE TITLE
TESS:T passband fails for atm='blackbody'

### ISSUE THREAD

**Issue by gecheline** [phoebe-project/phoebe2#366]
Error says "system failed to pass checks\nRun Checks Report: FAIL\nERROR: 'TESS:T' passband (passband@lc01@lc@dataset) does not support atm='blackbody' (atm@_default@phoebe01@phoebe@compute)"

**Comment by gecheline** [comment]
it's not just 'blackbody', 'ck2004' raises the same error.

**Comment by aprsa** [comment]
Hmmm, I can't reproduce; could you please send me the example script? I tried:

```
>>> pb = phoebe.get_passband('TESS:T')
>>> pb.version
1.0
>>> pb.timestamp
'Sun Dec 22 10:12:26 2019'
>>> pb.Inorm(Teff=5772., atm='blackbody')
array([2.06067608e+13])
>>> pb.Inorm(Teff=5772., logg=4.43, abun=0.02, atm='ck2004')
array([2.06499423e+13])
```

**Comment by kecnry** [comment]
The actual issue here was that *exported* scripts were disabling online passbands (to try to be lightweight)... the checks that were throwing the error were checking against the available online tables which were never queried and so thought they weren't available.  Exporting scripts no longer disables online passbands (especially with changes in 2.2 to only pull requested subtables for atmospheres, see f6822b122c78e3c8a21bb474f8d190f3d8c36124 and b871c7fc171301553108f072d304eb41736209bb).  In the future, we may want to make the error messages smarter for the cases where online passbands are intentionally disabled by the user via the environment variable.  There is a disclaimer on the documentation that you should be sure you have all necessary tables installed before manually disabling this option (see http://phoebe-project.org/docs/2.2/tutorials/optimizing)
