### ISSUE TITLE
Could not compute ldint with ldatm='ck2004'

### ISSUE THREAD

**Issue by mkounkel** [phoebe-project/phoebe2#412]
Forked from https://github.com/phoebe-project/phoebe2-ui/issues/5

When trying to run phoebe, I get the error of 

Error: Job failed with error: ValueError: Could not compute ldint with ldatm='ck2004'. Try changing atm to a table that covers a sufficient range of values. If necessary, set atm to 'blackbody' and/or ld_mode to 'manual' (in which case coefficients will need to be explicitly provided via ld_coeffs). Enable 'warning' logger to see out-of-bound arrays.

This occurred in the tutorials, on the web interface with the default parameters, and after changing the parameters extensively, on detached and semi-detached binary (surprisingly, contact binary doesn't give this issue, though it has its own slew of delightful error messages). Also, web interface doesn't allow me to change ld_coeffs.

**Comment by kecnry** [comment]
The atmosphere table (by default) is castelli-kurucz (ck2004) which only covers a range of local temperatures, loggs, metallicities, etc.  When any surface element falls outside of those limits, this error is raised with instructions on your options.  Unless this message occurs when it shouldn't, this is (albeit frustrating and annoying) expected behavior.

This should not happen directly for the default system.  If you just do the bare basics (below) do you still get this error? 

```
import phoebe
b = phoebe.default_binary()
b.add_dataset('lc', compute_phases=phoebe.linspace(0,1,11))
b.run_compute()
b.plot(show=True)
```

If you get the error message for this, then there may be a bug.  If you do not, then everything is *probably* working as designed, and you'll need to either fallback on blackbody atmospheres (with `b.set_value_all('atm', 'blackbody')`) and set limb-darkening coefficients manually (with `b.set_value_all('ld_mode', 'manual')` at which point the 'ld_func' and 'ld_coeffs' parameters will become "visible" and you can set them).  For more details, see the [atmospheres and passbands](http://phoebe-project.org/docs/latest/tutorials/atm_passbands) and [limb-darkening](http://phoebe-project.org/docs/latest/tutorials/limb_darkening) tutorials.

If you think your script shouldn't be raising this error message, then please send us the script and we can try to reproduce on our ends or let you know why it is falling outside of the atmosphere grids.
