### ISSUE TITLE
test on windows

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#43]

**Comment by horvatm** [comment]
I have installed Windows 10 in Virtualbox. Maybe we can test Phoebe there.

**Comment by horvatm** [comment]
On Windows 10 Education (64-bit) I have installed
```
  GitKraken (for git)
  Visual Studio 2015 Enterprise with Common tools installed (for C++ compiler)  
  Anaconda 4.1.1 (for python 2.7.12)
```
I have tried many things, but the build process
```
python setup.py build
```
fails with messages
```
.....
Missing compiler_cxx fix for MSVCCompiler
....
don't know how to compile Fortran code on platform 'nt'
warning: build_ext: f77_compiler=None is not available.

building 'phoebe_burlishstoer' extension
compiling C sources
error: Unable to find vcvarsall.bat
```
I thinks I tried all noninvasive hacks, but did not make it. I think we have a compatibility issue with new VS and we are missing Fortran compiler. 

For this to fix we need a Windows, VS and Python guy.

**Comment by giammarc** [comment]
"I'm a windows guy", said no-one ever!  Sorry, no offense, just a little 
humor.

--------------

Correct me if I'm wrong, but...

|building 'phoebe_burlishstoer' extension compiling C sources error: 
Unable to find vcvarsall.bat |

I thought this was replaced?  Did I miss something?

**Comment by kecnry** [comment]
@giammarc - no, phoebe_burlishstoer is still used for nbody dynamics (not included in the upcoming beta-release).  I did implement rebound for nbody as well, but testing didn't show it performing quite well enough to make a full replacement (yet).

That said - if the only hold-up is burlishstoer, we can definitely exclude that for the release.  However, I expect all the cpp code will fail to build and this is just the first one in the line.

**Comment by horvatm** [comment]
With the following modifications it builds successfully:
I. Copy 
```
vcvarsall.bat
```
from
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
```
to
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools
```
In command prompt of Visual studio set variable
```
SET VS90COMNTOOLS=%VS140COMNTOOLS%
```
II. For the case of MS Visual Studio commend out CXX and -std=c++11.

III.  It seems that Virtual studio 64bit does not support inline assembler and therefore we need to add in setup.py compiler flag 
```
/DTARGET_HAS_SINCOS=0
```
to disable fast calculation of sin+cos with one command.

Ref:  /D (Preprocessor Definitions)
https://msdn.microsoft.com/en-us/library/hhzbb5c8.aspx

**Comment by kecnry** [comment]
once we switch to the new atmcof implementation (see #51), then we should be able to build on windows.

**Comment by kecnry** [comment]
#51 is now closed - we no longer depend on any fortran code so, in theory, we should now be able to build and test on windows

**Comment by horvatm** [comment]
It seems that VS 14.0 does not like the BS code:

:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda2\lib\site-packages\numpy\core\include -IC:\Anaconda2\include -IC:\Anaconda2\PC /Tp./phoebe/algorithms/b
urlishstoer/phoebe_BS_nbody.cpp /Fobuild\temp.win-amd64-2.7\Release\./phoebe/algorithms/burlishstoer/phoebe_BS_nbody.obj /Zm1000
Found executable C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda2\lib\site-packages\numpy\core\include -IC:\Anaconda2\include -IC:\Anaconda2\PC /Tp./phoebe/algorithms/b
urlishstoer/n_body.cpp /Fobuild\temp.win-amd64-2.7\Release\./phoebe/algorithms/burlishstoer/n_body.obj /Zm1000
n_body.cpp
./phoebe/algorithms/burlishstoer/n_body.cpp(39): warning C4101: 'rat': unreferenced local variable
./phoebe/algorithms/burlishstoer/n_body.cpp(73): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
./phoebe/algorithms/burlishstoer/n_body.cpp(117): error C2131: expression did not evaluate to a constant
./phoebe/algorithms/burlishstoer/n_body.cpp(117): note: failure was caused by non-constant arguments or reference to a non-constant symbol
./phoebe/algorithms/burlishstoer/n_body.cpp(117): note: see usage of 'N'
./phoebe/algorithms/burlishstoer/n_body.cpp(126): error C3863: array type 'double [N][N][3]' is not assignable
./phoebe/algorithms/burlishstoer/n_body.cpp(127): error C3863: array type 'double [N][N][3]' is not assignable
./phoebe/algorithms/burlishstoer/n_body.cpp(128): error C3863: array type 'double [N][N][3]' is not assignable
.....

**Comment by kecnry** [comment]
currently working on getting a CI setup for windows via appveyor (in the windows_support branch), but it seems they don't have any free plans (currently just testing on a 14-day trial).  So we may need to consider switching to tea-CI... but this will get complicated since astropy's ci-helper only supports travis and appveyor.

**Comment by kecnry** [comment]
windows now builds and seems to run successfully (in the development branch).  Still working on getting appveyor up and running correctly (in the windows_testing branch)

**Comment by horvatm** [comment]
I am working on Windows 10 Enterprise 2016 x64 in VirtualBox 5.2. To **compile and run phoebe 2** I do the following:

1. Install Visual Studio 2017 Community  and following "packages":

  - Python development workload 
  - Desktop development with C++ workload
  - Native development tools option.

For running of phoebe 2 one needs only some additional dlls:

    msvcp140.dll
    vcruntime140.dll
    ucrtbase.dll

that are installed via Visual C++ Redistributable for Visual Studio 2017 (64 bit)  (I THINK) and can be found:

    http://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe
  
2. Install git:  https://git-scm.com/download/win

3. Install python 2.7 for x64:   
      https://www.python.org/downloads/
   but this could also work with anaconda 2 from 
      https://www.anaconda.com/download/
  
4. Install packages
 ```
  python -m pip install --upgrade pip # necessary for installation
  python -m pip install --upgrade readline numpy astropy scipy pyreadline # neccessary for running
  python -m pip install --upgrade matplotlib sympy # recommended
```
  pyreadline is replacement for GNU readline. We could potentially do in 
  phoebe:
```
  try:
    import readline
  except ImportError:
    import pyreadline as readline
```
  
4. Install phoebe2:
```
  git clone https://github.com/phoebe-project/phoebe2.git

  cd  phoebe2

  call vars_VS2017Community.bat
  python setup.py build
  python setup.py install --user
```  
5. For binary package do
  a. Change version in setup.py to float: 2.1
  b. Run setup.py as
```    
    python setup.py bdist --format=msi
```
This will generate a installer package  [phoebe-2.1.win-amd64-py2.7.msi](https://www.dropbox.com/s/d70gxqsx9jitjtg/phoebe-2.1.win-amd64-py2.7.msi?dl=0) in /]dist.

For **just running phoebe 2** one can do the follow. 

1. Install and update python 2.7 with necessary packages

2. Download install binary package phoebe-2.1.win-amd64-py2.7.msi 

This was tested on freshly installed windows 10 + anaconda 2.

**Comment by horvatm** [comment]
I consider this as done.
