### ISSUE TITLE
WD triangular mesh has some degenerate triangles

### ISSUE THREAD

**Issue by horvatm** [phoebe-project/phoebe2#53]
The triangular mesh generated from WD surface discretization has some triangles with zero area, which could affect algorithms using them.

**Comment by aprsa** [comment]
How dire is this? I can fix it more-or-less straightforwardly, but it will mess up the 1:1 analogy with WD.

**Comment by horvatm** [comment]
It can be only a problem, if this is not expected. If WD mesh won't be used with other libphoebe routines then this is irrelevant. @kecnry can you comment on this.

**Comment by kecnry** [comment]
I don't see any problems with the zero-area triangles.  Libphoebe's eclipsing fails on WD-meshes for many other and bigger reasons, and I haven't seen any of the other routines running into issues.

In the end, these triangles are ignored in the integration anyways because they have zero area, so as long as they don't cause a complete crash, I don't think its worth putting effort into fixing it **and** having to handle the exception when comparing meshes vs WD.

**Comment by horvatm** [comment]
Then I will relabel this into annoyance.

**Comment by horvatm** [comment]
This is not needed anymore in Phoebe 2.x
