### ISSUE TITLE
rotstar spot support broken in 2.4.9

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#716]
Reported by Marcin Wrona:

I have the newest version of the PHOEBE - 2.4.9. The bug concerns running a single star with a spot.

I wanted to run my own code but it kept failing, so I decided to test a code from the tutorial and I got the same result. I also tested it on the Web UI Client and got the same problem.

The code is crashing on b.run_compute() with an error "AttributeError: 'Star_rotstar' object has no attribute 'F'".

Here's the code from the tutorial:

```
import phoebe
from phoebe import u # units
import numpy as np
import matplotlib.pyplot as plt

logger = phoebe.logger()

b = phoebe.default_star()

b.add_spot(radius=30, colat=80, long=0, relteff=0.9)
#print(b['spot'])

times = np.linspace(0, 10, 11)
b.set_value('period', 10)
b.add_dataset('mesh', times=times, columns=['teffs'])

b.run_compute(distortion_method='rotstar', irrad_method='none')
```

**Comment by kecnry** [comment]
Long term I think the solution is to push the responsibility of `needs_recompute_instantaneous` for asynchronous spots down to the features themselves.  So `needs_recompute_instantaneous` for the base `Star` class could become `self.needs_remesh or np.any([feature.needs_recompute_instantaneous for feature in self.features])`  (although probably optimized with a loop instead of the list-comprehension) and we can entirely remove the override in `Star_rotstar`.  That would then mean that this spot-specific logic isn’t automatically inherited by pulsations as well.  Then the `Spot.from_bundle` can store whatever it needs to store in the existing if-else statement for binary vs single-star cases,

**Comment by aprsa** [comment]
The fact that a single star and a star in a binary are rotated differently doesn't help. A star in a binary will have its mesh rotated about its spin axis while a single star will not. That is why `dlongdt` means something different for single and binary stars: dlongdt needs to be 0 for synchronous rotation in a binary, but `2*pi*dphi` for a single star. Thus, spots on single stars must _always_ recompute instantaneous mesh values. I assume that, generally, rotation will be cheaper than repopulating the mesh.

We might want to consider moving mesh rotation from the binary to the star itself, while keeping mesh revolution (orbital) transformation in the binary. It will include numerical noise from discretization and it will allow us to simply rotate a featureful mesh without repopulating it. The price to pay is that syncpar will be a constrained parameter by default, determined by Porb and Prot (and other parameters in the case of dperdt, dpdt, ... != 0). Another benefit will be that dlongdt interpretation becomes unified.
