### ISSUE TITLE
reflection using blackbody intensities instead of atm fluxes

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#91]
Intensities used as input to reflection are currently hardcoded to always use atm='blackbody'.  They should instead use the per-component atms (see also #90), but with limb-darkening disabled (limb-darkening is then re-handled within reflection).

See phoebe.backend.universe.System.populate_observables

ld_func_bol and ld_coeffs_bol were also not being passed correctly to libphoebe's reflection

**Comment by kecnry** [comment]
I'm making progress on this, but ran into a problem (which is probably why I temporarily ignored atmospheres when first implementing reflection).

@aprsa - do we not support atm='extern_planckint' (extern_wd_idx) with passband='Bolometric:1760-40000'?  In order for reflection to work, we're going to need *all* atmospheres to work with the bolometric passband.  If this isn't possible, then we'll need to implement a check that doesn't allow reflection to be enabled for atmospheres that don't support a bolometric passband, or we'll have to fallback on some other passband/atmosphere combination.  Thoughts?

**Comment by aprsa** [comment]
Why do we need bolometric atmospheres for reflection? I thought we only needed bolometric LD coefficients for the Wilson (1990) scheme to work?

planckint and atmx won't ever support bolometric atmospheres because WD doesn't support them. We can of course fall back, but let me first understand why we need them in the first place.
